import React, { useState } from 'react';
import Card from '../../../components/ui/Card';
import Button from '../../../components/ui/Button';
import { Download, FileText, Filter, Loader } from 'lucide-react';
import { useToast } from '../../../components/ui/Toast';
import { generatePDF } from '../../../utils/pdfGenerator';
import { useLocation } from 'react-router-dom';

export default function ParentReports() {
  const { success } = useToast();
  const location = useLocation();
  const [selectedChild, setSelectedChild] = useState(location.state?.child || 'All');
  const [downloadingId, setDownloadingId] = useState(null);

  const reports = [
    { id: 1, title: 'Alex – Fall 2026 Report Card', child: 'Alex Johnson', date: 'Oct 15, 2026', type: 'Academic' },
    { id: 2, title: 'Mia – Fall 2026 Report Card', child: 'Mia Johnson', date: 'Oct 15, 2026', type: 'Academic' },
    { id: 3, title: 'Alex – Spring 2026 Transcript', child: 'Alex Johnson', date: 'Jun 20, 2026', type: 'Transcript' },
    { id: 4, title: 'Mia – Spring 2026 Transcript', child: 'Mia Johnson', date: 'Jun 20, 2026', type: 'Transcript' },
    { id: 5, title: 'Alex – Behavioral Assessment', child: 'Alex Johnson', date: 'Sep 30, 2026', type: 'Conduct' },
  ];

  const filteredReports = selectedChild === 'All' 
    ? reports 
    : reports.filter(r => r.child === selectedChild);

  const handleDownload = (report) => {
    setDownloadingId(report.id);
    setTimeout(() => {
      const columns = ['Record Detail', 'Information'];
      const rows = [
        ['Report Title', report.title],
        ['Student Name', report.child],
        ['Report Date', report.date],
        ['Category', report.type],
        ['Generated By', 'EduSaaS Parent Portal'],
      ];
      
      generatePDF(report.title, columns, rows, `${report.title.toLowerCase().replace(/ /g, '_')}.pdf`);
      setDownloadingId(null);
      success(`${report.title} downloaded successfully.`);
    }, 1200);
  };

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
        <h1 style={{ fontSize: '2rem' }}>Reports & Official Documents</h1>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', background: 'var(--color-bg)', padding: '0.5rem 1rem', borderRadius: 'var(--radius-lg)', border: '1px solid var(--color-border)' }}>
            <Filter size={16} color="var(--color-text-muted)" />
            <span style={{ fontSize: '0.875rem', fontWeight: '600', color: 'var(--color-text-muted)' }}>Child:</span>
            <select 
              value={selectedChild}
              onChange={(e) => setSelectedChild(e.target.value)}
              style={{ background: 'transparent', border: 'none', outline: 'none', color: 'var(--color-text-main)', fontSize: '0.875rem', fontWeight: '600', cursor: 'pointer' }}
            >
                <option value="All">All Children</option>
                <option value="Alex Johnson">Alex Johnson</option>
                <option value="Mia Johnson">Mia Johnson</option>
            </select>
        </div>
      </div>

      <Card style={{ padding: 0, overflow: 'hidden', border: '1px solid var(--color-border)' }}>
        <div style={{ padding: '1.5rem 2rem', borderBottom: '1px solid var(--color-border)', background: 'var(--color-surface)' }}>
          <h3 style={{ margin: 0, fontSize: '1.1rem' }}>Available For Download</h3>
        </div>
        <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
              <thead>
                <tr style={{ background: 'var(--color-bg)', color: 'var(--color-text-muted)', fontSize: '0.8rem', textTransform: 'uppercase', letterSpacing: '1px' }}>
                  <th style={{ padding: '1.25rem 2rem', fontWeight: '700' }}>Document Name</th>
                  <th style={{ padding: '1.25rem 2rem', fontWeight: '700' }}>Child</th>
                  <th style={{ padding: '1.25rem 2rem', fontWeight: '700' }}>Issue Date</th>
                  <th style={{ padding: '1.25rem 2rem', fontWeight: '700', textAlign: 'right' }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {filteredReports.map((r) => (
                  <tr key={r.id} style={{ borderBottom: '1px solid var(--color-border)', transition: 'background 0.2s' }}>
                    <td style={{ padding: '1.25rem 2rem' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                          <div style={{ width: '40px', height: '40px', borderRadius: 'var(--radius-md)', background: 'rgba(79, 70, 229, 0.1)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                            <FileText size={20} color="var(--color-primary)"/>
                          </div>
                          <div>
                              <div style={{ fontWeight: '600', color: 'var(--color-text-main)' }}>{r.title}</div>
                              <div style={{ fontSize: '0.75rem', color: 'var(--color-text-muted)' }}>{r.type} Document</div>
                          </div>
                      </div>
                    </td>
                    <td style={{ padding: '1.25rem 2rem', color: 'var(--color-text-body)', fontWeight: '500' }}>{r.child}</td>
                    <td style={{ padding: '1.25rem 2rem', color: 'var(--color-text-muted)', fontSize: '0.9rem' }}>{r.date}</td>
                    <td style={{ padding: '1.25rem 2rem', textAlign: 'right' }}>
                      <Button 
                        variant="outline" 
                        size="sm" 
                        onClick={() => handleDownload(r)}
                        disabled={downloadingId === r.id}
                        style={{ minWidth: '120px', justifyContent: 'center' }}
                      >
                        {downloadingId === r.id ? <Loader size={16} className="spin" style={{ marginRight: 8 }} /> : <Download size={16} style={{ marginRight: 8 }}/>}
                        {downloadingId === r.id ? 'Generating...' : 'Download PDF'}
                      </Button>
                    </td>
                  </tr>
                ))}
                {filteredReports.length === 0 && (
                    <tr>
                        <td colSpan="4" style={{ padding: '4rem', textAlign: 'center', color: 'var(--color-text-muted)' }}>
                            No matching reports found.
                        </td>
                    </tr>
                )}
              </tbody>
            </table>
        </div>
      </Card>

      <div style={{ marginTop: '2rem', display: 'flex', gap: '1.5rem' }}>
          <Card style={{ flex: 1, borderLeft: '4px solid var(--color-primary)' }}>
              <div style={{ fontSize: '0.875rem', color: 'var(--color-text-muted)', marginBottom: '0.5rem', fontWeight: '600' }}>Total Available Docs</div>
              <div style={{ fontSize: '1.75rem', fontWeight: '800', color: 'var(--color-text-main)' }}>{reports.length}</div>
          </Card>
          <Card style={{ flex: 1, borderLeft: '4px solid var(--color-success)' }}>
              <div style={{ fontSize: '0.875rem', color: 'var(--color-text-muted)', marginBottom: '0.5rem', fontWeight: '600' }}>Last Downloaded</div>
              <div style={{ fontSize: '1rem', fontWeight: '700', color: 'var(--color-text-main)' }}>None this session</div>
          </Card>
      </div>
    </div>
  );
}
