import React, { useState } from 'react';
import Card from '../../../components/ui/Card';
import Button from '../../../components/ui/Button';
import { Download, FileText, PieChart, BarChart2, TrendingUp, Users, Loader } from 'lucide-react';
import { useToast } from '../../../components/ui/Toast';
import Modal from '../../../components/ui/Modal';
import { generatePDF } from '../../../utils/pdfGenerator';

export default function AdminReports() {
  const { success } = useToast();
  const [downloadingId, setDownloadingId] = useState(null);
  const [isExplorerOpen, setIsExplorerOpen] = useState(false);

  const reports = [
    { id: 1, title: 'Annual Financial Summary 2026', type: 'Finance', date: 'Oct 20, 2026', size: '2.4 MB' },
    { id: 2, title: 'Student Enrollment Analytics', type: 'Academic', date: 'Oct 15, 2026', size: '1.8 MB' },
    { id: 3, title: 'Teacher Performance Reviews Q3', type: 'HR', date: 'Oct 05, 2026', size: '3.1 MB' },
    { id: 4, title: 'Infrastructure & Asset Audit', type: 'Admin', date: 'Sep 28, 2026', size: '0.9 MB' },
    { id: 5, title: 'Departmental Budget Allocation', type: 'Finance', date: 'Sep 15, 2026', size: '4.2 MB' },
  ];

  const handleDownload = (report) => {
    setDownloadingId(report.id);
    // Simulate generation delay
    setTimeout(() => {
        const columns = ['Metric', 'Value'];
        const rows = [
            ['Total Enrollment', '1,245 Students'],
            ['Growth Rate', '+5.2%'],
            ['Revenue MTD', '$124,500'],
            ['Outstanding Dues', '$45,200'],
            ['Generated By', 'EduSaaS Admin System'],
        ];
        
        generatePDF(report.title, columns, rows, `${report.title.toLowerCase().replace(/ /g, '_')}.pdf`);
        setDownloadingId(null);
        success(`${report.title} is now ready for download.`);
    }, 1500);
  };

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
        <div>
          <h1 style={{ fontSize: '2rem' }}>Institutional Reports</h1>
          <p style={{ color: 'var(--color-text-muted)', margin: 0 }}>Access system-wide analytical data and formal documentation</p>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '1.5rem', marginBottom: '2.5rem' }}>
          {[
              { label: 'Active Reports', value: '42', icon: <FileText size={20}/>, color: 'var(--color-primary)' },
              { label: 'Average Growth', value: '12%', icon: <TrendingUp size={20}/>, color: 'var(--color-success)' },
              { label: 'Total Capacity', value: '92%', icon: <Users size={20}/>, color: 'var(--color-secondary)' },
              { label: 'Audit Status', value: 'Clear', icon: <PieChart size={20}/>, color: 'var(--color-accent)' },
          ].map((stat, i) => (
              <Card key={i} style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                  <div style={{ color: stat.color, marginBottom: '0.25rem' }}>{stat.icon}</div>
                  <div style={{ fontSize: '1.75rem', fontWeight: '800', color: 'var(--color-text-main)' }}>{stat.value}</div>
                  <div style={{ fontSize: '0.75rem', color: 'var(--color-text-muted)', fontWeight: '700', textTransform: 'uppercase' }}>{stat.label}</div>
              </Card>
          ))}
      </div>

      <Card style={{ padding: 0, overflow: 'hidden', border: '1px solid var(--color-border)' }}>
        <div style={{ padding: '1.5rem 2rem', borderBottom: '1px solid var(--color-border)', background: 'var(--color-surface)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <h3 style={{ margin: 0, fontSize: '1.2rem' }}>Available Analytical Documents</h3>
            <Button variant="outline" size="sm" onClick={() => setIsExplorerOpen(true)}><BarChart2 size={16} /> Data Explorer</Button>
        </div>
        <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
              <thead>
                <tr style={{ background: 'var(--color-bg)', color: 'var(--color-text-muted)', fontSize: '0.8rem', textTransform: 'uppercase', letterSpacing: '1px' }}>
                  <th style={{ padding: '1.25rem 2rem', fontWeight: '700' }}>Document Title</th>
                  <th style={{ padding: '1.25rem 2rem', fontWeight: '700' }}>Category</th>
                  <th style={{ padding: '1.25rem 2rem', fontWeight: '700' }}>Issue Date</th>
                  <th style={{ padding: '1.25rem 2rem', fontWeight: '700', textAlign: 'right' }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {reports.map((r) => (
                  <tr key={r.id} style={{ borderBottom: '1px solid var(--color-border)', transition: 'background 0.2s' }}>
                    <td style={{ padding: '1.25rem 2rem' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                          <div style={{ width: '44px', height: '44px', borderRadius: 'var(--radius-lg)', background: 'var(--color-primary-light)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                            <FileText size={22} color="var(--color-primary)"/>
                          </div>
                          <div>
                              <div style={{ fontWeight: '700', color: 'var(--color-text-main)', fontSize: '1rem' }}>{r.title}</div>
                              <div style={{ fontSize: '0.75rem', color: 'var(--color-text-muted)', fontWeight: '600' }}>{r.size} • PDF Generation Support</div>
                          </div>
                      </div>
                    </td>
                    <td style={{ padding: '1.25rem 2rem' }}>
                        <span style={{ 
                            padding: '0.3rem 0.75rem', borderRadius: '1rem', fontSize: '0.75rem', fontWeight: '700',
                            background: 'var(--color-bg)', color: 'var(--color-text-muted)', border: '1px solid var(--color-border)'
                        }}>{r.type}</span>
                    </td>
                    <td style={{ padding: '1.25rem 2rem', color: 'var(--color-text-muted)', fontWeight: '500', fontSize: '0.9rem' }}>{r.date}</td>
                    <td style={{ padding: '1.25rem 2rem', textAlign: 'right' }}>
                      <Button 
                        variant="outline" 
                        size="sm" 
                        onClick={() => handleDownload(r)}
                        disabled={downloadingId === r.id}
                        style={{ minWidth: '130px', justifyContent: 'center', gap: '0.5rem' }}
                      >
                        {downloadingId === r.id ? <Loader size={16} className="spin" /> : <Download size={16} />}
                        {downloadingId === r.id ? 'Processing...' : 'Export PDF'}
                      </Button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
        </div>
      </Card>

      {/* Data Explorer Modal */}
      <Modal isOpen={isExplorerOpen} onClose={() => setIsExplorerOpen(false)} title="Data Explorer">
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
          <p style={{ color: 'var(--color-text-muted)' }}>Query and analyze your institutional data across all modules.</p>
          
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
            <div>
              <label style={{ display: 'block', fontSize: '0.875rem', fontWeight: '500', marginBottom: '0.5rem' }}>Data Source</label>
              <select style={{ width: '100%', padding: '0.75rem 1rem', borderRadius: 'var(--radius-md)', border: '1px solid var(--color-border)', outline: 'none' }}>
                <option>Financial Records</option>
                <option>Student Enrollment</option>
                <option>Faculty Performance</option>
              </select>
            </div>
            <div>
              <label style={{ display: 'block', fontSize: '0.875rem', fontWeight: '500', marginBottom: '0.5rem' }}>Time Range</label>
              <select style={{ width: '100%', padding: '0.75rem 1rem', borderRadius: 'var(--radius-md)', border: '1px solid var(--color-border)', outline: 'none' }}>
                <option>Last 30 Days</option>
                <option>This Quarter</option>
                <option>Year to Date</option>
              </select>
            </div>
          </div>

          <div style={{ padding: '2rem', background: 'var(--color-bg)', borderRadius: 'var(--radius-lg)', border: '1px dashed var(--color-border)', textAlign: 'center', color: 'var(--color-text-muted)' }}>
             <BarChart2 size={48} style={{ margin: '0 auto 1rem', opacity: 0.5 }} />
             Select parameters to generate visualization
          </div>

          <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '1rem', marginTop: '1rem' }}>
            <Button variant="outline" onClick={() => setIsExplorerOpen(false)}>Cancel</Button>
            <Button variant="primary" onClick={() => { setIsExplorerOpen(false); success('Query execution simulated.'); }}>Run Query</Button>
          </div>
        </div>
      </Modal>
    </div>
  );
}
